version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<your-task-definition>"
        LoadBalancerInfo:
          ContainerName: "mediawiki-app"
          ContainerPort: 80
