version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Instalando dependências..."
  pre_build:
    commands:
      - echo "Iniciando o processo de build"
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your-ecr-repo>)
  build:
    commands:
      - echo "Construindo a imagem Docker do MediaWiki"
      - docker build -t mediawiki-app .
      - docker tag mediawiki-app:latest <your-ecr-repo>:latest
  post_build:
    commands:
      - echo "Enviando a imagem para o ECR"
      - docker push <your-ecr-repo>:latest

artifacts:
  files:
    - '**/*'

